version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: training_management_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Set the root password for MySQL
      MYSQL_DATABASE: training_management  # Name of the database to create
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount your init.sql file
    ports:
      - "3307:3306"  # Expose MySQL port
    networks:
      - training_management_network

networks:
  training_management_network:
    driver: bridge
